---
AWSTemplateFormatVersion: 2010-09-09

Description: CDN Container

Parameters:
  RunEnvironment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Description: Set environment state


Resources:
  S3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub Your-Bucket-Name-${RunEnvironment}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${S3}/*
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OAI}

  CloudFront:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          PriceClass: PriceClass_All
          ViewerCertificate:
            CloudFrontDefaultCertificate: true
          DefaultCacheBehavior:
            TargetOriginId: !GetAtt S3.DomainName
            ViewerProtocolPolicy: https-only
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Origins:
            - DomainName: !GetAtt S3.DomainName
              Id: !GetAtt S3.DomainName
              S3OriginConfig:
                OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OAI}
      DependsOn: OAI

  OAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'OAI for cdn container bucket.'
    DependsOn: S3
