apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {TARGET_BRANCH}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {YourGitRepo}
    targetRevision: {TARGET_BRANCH}
    path: ./

  destination:
    server: https://kubernetes.default.svc
    namespace: default
